title: Ian Knighton
lang: en
email: ian@knighton.dev
description: >- 
  I'm only pretending I know what I'm doing. 
baseurl: "" 
url: "https://IanKnighton.github.io" 

timezone: America/Boise

# Social Networks
github_username:  IanKnighton
linkedin_username: ianknighton1

# Build settings
theme: minima
plugins:
  - jekyll-feed
